import { ExperienceImage } from '@/components/ExperienceImage'
import type { ExperienceAssetId } from '@/lib/experience-assets'

const experiences = [
  {id:'01',title:'The House Is the Attraction',type:'Master Principle',description:'The property is designed as a destination in its own right—not a restaurant with themed rooms. Food, culture, sound, art and hospitality operate as one authored world.',systems:['Architecture','Arrival ritual','Guest circulation','Hospitality operations'],status:82},
  {id:'02',title:'Every Room Is Its Own World',type:'Spatial Experience',description:'Each environment receives an independent story, soundtrack, emotional tone, material language, lighting system, scent profile and reason to reserve again.',systems:['Interior identity','Lighting scenes','Sound profile','Scent and material palette'],status:68},
  {id:'03',title:'Private Salons and Hosted Experiences',type:'Hospitality Program',description:'Invitation-led listening sessions, private dinners, intimate performances, artist conversations and creative salons built for small groups and controlled access.',systems:['Reservation logic','Acoustics','Service choreography','Flexible furniture'],status:55},
  {id:'04',title:'Hidden Rooms, Doors and Reveals',type:'Discovery System',description:'Secret passages, concealed thresholds, changing environments and unexpected moments reward curiosity and make repeat visits structurally different.',systems:['Architectural concealment','Safety and egress','Interactive triggers','Repeat-visit programming'],status:46},
  {id:'05',title:'Music as Architecture',type:'Audio Experience',description:'Music is not background. Genres, eras, listening rituals, live moments and high-fidelity playback shape the behavior and emotional temperature of each room.',systems:['Zoned audio','Acoustic isolation','Playback standards','Performance infrastructure'],status:61},
  {id:'06',title:'The Living Gallery',type:'Art and Culture',description:'Rotating artwork, artist commissions, temporary installations and evolving collections keep the house culturally alive instead of frozen at opening day.',systems:['Curatorial calendar','Art handling','Lighting flexibility','Rights and insurance'],status:42},
  {id:'07',title:'Legendary Creative Residence Energy',type:'Design Standard',description:'The atmosphere must feel like entry into an iconic musician or collector’s private home—layered, personal, luxurious, edgy and never conventionally formal.',systems:['Residential scale','Collected furnishings','Art direction','Material authenticity'],status:76},
  {id:'08',title:'Dining as One Chapter',type:'Culinary Integration',description:'Food is woven into performance, storytelling, projection, ritual, conversation and room-specific service rather than treated as the entire reason for the visit.',systems:['Culinary choreography','Service routes','Media cues','Room-specific menus'],status:39},
  {id:'09',title:'Emotionally Programmed Rooms',type:'Guest Journey',description:'Each space is intentionally engineered around a feeling—nostalgia, intimacy, curiosity, celebration, reflection, inspiration or release.',systems:['Emotional brief','Lighting and sound cues','Scent','Host scripting'],status:58},
  {id:'10',title:'International Experience System',type:'Expansion Architecture',description:'The concept must be repeatable internationally without becoming a copy-and-paste franchise. Core rituals stay protected while art, music, food and cultural layers localize by market.',systems:['Global standards','Local cultural curation','Modular technology','Licensing and brand governance'],status:28},
]

export default function FullExperience(){return <main><section className="section experience-hero"><div className="shell"><div className="eyebrow">/full experience · mandatory program</div><h2>The house is the headline.</h2><p className="sectionintro">These concepts are the fixed creative brief from the recorded discovery. Every architectural, operational, technical and financial decision must protect them as the project develops.</p><div className="callout"><strong>Non-negotiable:</strong> this cannot resolve into a conventional luxury restaurant, a single repeated visual theme or a collection of decorative photo moments. It must operate as a living cultural destination.</div><div className="grid experience-grid">{experiences.map((experience,index)=><article className={`card experience-card ${index%3===0?'span8':'span4'}`} key={experience.id}><div className="card-topline"><div className="num">{experience.id} · {experience.type}</div><span className="pill active">Required</span></div><ExperienceImage id={`experience-${experience.id}` as ExperienceAssetId} sizes="(max-width:800px) 100vw, 66vw" /><h3>{experience.title}</h3><p>{experience.description}</p><div className="system-list">{experience.systems.map(system=><span key={system}>{system}</span>)}</div><div className="bar"><span style={{width:`${experience.status}%`}} /></div><p className="muted">Definition and engineering readiness · {experience.status}%</p></article>)}</div></div></section></main>}
