const phases = [
['01','Experience Foundation + Digital MVP','$18,500','Recorded-discovery synthesis, master experience doctrine, mandatory experience registry, landing site, virtual-tour framework, client scope, progress portal, production dashboard and executive deck foundation.'],
['02','Story, Guest Journey + Spatial Programming','$25,000–$40,000','Property programming, room hierarchy, hidden-moment strategy, private-experience logic, emotional journey, circulation, capacity, adjacencies and international adaptation rules.'],
['03','Priority Room Design Development','$45,000–$75,000','Detailed concepts for approved priority environments, materials, furnishings, lighting language, art direction, custom features and presentation render packages.'],
['04','Experience Engineering + Technology','$30,000–$60,000','Audio, acoustics, lighting controls, projection, interactive triggers, scent, media, hidden-room systems and technical coordination briefs.'],
['05','Brand World, Digital Twin + Launch','$25,000–$45,000','Identity extensions, menus, collateral, virtual-tour expansion, launch narrative, photography and film direction, social system and press-facing assets.'],
['06','Production Oversight + Opening Calibration','$8,000–$14,000/mo','Vendor and fabricator review, design-intent protection, site coordination, installation direction, punch-list review, soft-opening calibration and launch supervision.']]
const phaseOneLines=[['Discovery synthesis + experience doctrine','$3,000'],['Guest journey + mandatory experience registry','$3,250'],['Landing page + overall digital experience','$4,250'],['Virtual-tour structure + content architecture','$2,750'],['Client scope, progress portal + production dashboard','$3,250'],['Executive deck foundation + presentation narrative','$2,000']]
export default function Scope(){return <main><section className="section"><div className="shell"><div className="eyebrow">/scope · client facing</div><h2>Phased to protect the vision, approvals and cash flow.</h2><p className="sectionintro">The engagement begins with a complete experience foundation and digital presentation environment. Later phases are authorized only after the property, priority rooms, technical ambition and rollout strategy are confirmed.</p><table className="table"><thead><tr><th>Phase</th><th>Investment</th><th>Deliverables</th><th>Status</th></tr></thead><tbody>{phases.map((phase,index)=><tr key={phase[0]}><td><strong>{phase[0]} · {phase[1]}</strong></td><td className="price">{phase[2]}</td><td>{phase[3]}</td><td><span className={`pill ${index===0?'active':''}`}>{index===0?'Ready to authorize':'Future phase'}</span></td></tr>)}</tbody></table><div className="grid"><article className="card span6"><div className="num">RECOMMENDED AUTHORIZATION</div><div className="metric">$18,500</div><p>Phase 01 creative fee with a 60% start deposit of <strong>$11,100</strong>, 25% milestone of <strong>$4,625</strong>, and 15% completion payment of <strong>$2,775</strong>.</p></article><article className="card span6"><div className="num">OPTIONAL PRIORITY SCHEDULE</div><div className="metric">+$4,000</div><p>Accelerated reviews, expanded visual exploration, additional executive presentation polish and two extra consolidated revision rounds.</p></article></div><div className="invoice-block"><div className="eyebrow">Phase 01 invoice structure</div>{phaseOneLines.map(line=><div className="invoice-line" key={line[0]}><span>{line[0]}</span><strong>{line[1]}</strong></div>)}<div className="invoice-line total"><span>Total Phase 01 creative fee</span><strong>$18,500</strong></div></div><div className="callout">Architecture, engineering stamps, permitting, construction, general contracting, fabrication, AV equipment, furniture purchasing, installation labor, travel and third-party production remain separately contracted.</div></div></section></main>}
